// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";
inline constexpr char kDisplayName[] = "Autarx";
inline constexpr char kVersion[] = "2.0.0";
inline constexpr std::int64_t kBuild = 1;
inline constexpr char kIdentifier[] = "site.jrtx.autarx.Autarx";
inline constexpr char kReleaseChannel[] = "stable";

struct ClusterDto {
  std::string path;
  std::vector<std::string> connected_ecus;
  std::vector<std::string> frames;
};

struct CommunicationDto {
  std::vector<ClusterDto> clusters;
  std::vector<std::string> orphan_frames;
  std::vector<std::string> orphan_pdus;
  std::vector<std::string> orphan_signals;
};

struct ObjectChangeDto {
  std::string change_type;
  std::string short_name;
  std::string semantic_kind;
  std::string absolute_path;
  std::string detail;
};

struct DiffDto {
  bool identical;
  std::vector<ObjectChangeDto> object_changes;
  std::int64_t reference_change_count;
};

struct ReferenceDto {
  std::string kind;
  std::string source_path;
  std::string source_element_path;
  std::string target_path;
  bool resolved;
};

struct SemanticObjectDto {
  std::string short_name;
  std::string element_type;
  std::string semantic_kind;
  std::string absolute_path;
  std::string source_file;
  std::int64_t unresolved_references;
};

struct TraceDto {
  std::string root;
  std::int64_t max_depth;
  std::vector<std::string> node_paths;
  std::vector<ReferenceDto> edges;
};

struct WorkspaceSummary {
  std::string source_path;
  std::int64_t file_count;
  std::int64_t identifiable_count;
  std::int64_t package_count;
  std::int64_t reference_count;
  std::int64_t unresolved_count;
  std::int64_t duplicate_count;
  std::int64_t file_error_count;
  std::optional<std::string> autosar_release;
  bool mixed_schema;
};

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_Bool(bool v) { return rivet::Value(v); }
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode__List_String_(std::vector<std::string> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_String(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_ClusterDto(ClusterDto const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_String(v.path)); r.push_back(encode__List_String_(v.connected_ecus)); r.push_back(encode__List_String_(v.frames)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_ClusterDto_(std::vector<ClusterDto> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_ClusterDto(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_CommunicationDto(CommunicationDto const& v) { rivet::Value::List r; r.reserve(4); r.push_back(encode__List_ClusterDto_(v.clusters)); r.push_back(encode__List_String_(v.orphan_frames)); r.push_back(encode__List_String_(v.orphan_pdus)); r.push_back(encode__List_String_(v.orphan_signals)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_ObjectChangeDto(ObjectChangeDto const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.change_type)); r.push_back(encode_String(v.short_name)); r.push_back(encode_String(v.semantic_kind)); r.push_back(encode_String(v.absolute_path)); r.push_back(encode_String(v.detail)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_ObjectChangeDto_(std::vector<ObjectChangeDto> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_ObjectChangeDto(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }
inline rivet::Value encode_DiffDto(DiffDto const& v) { rivet::Value::List r; r.reserve(3); r.push_back(encode_Bool(v.identical)); r.push_back(encode__List_ObjectChangeDto_(v.object_changes)); r.push_back(encode_Int64(v.reference_change_count)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_SemanticObjectDto(SemanticObjectDto const& v) { rivet::Value::List r; r.reserve(6); r.push_back(encode_String(v.short_name)); r.push_back(encode_String(v.element_type)); r.push_back(encode_String(v.semantic_kind)); r.push_back(encode_String(v.absolute_path)); r.push_back(encode_String(v.source_file)); r.push_back(encode_Int64(v.unresolved_references)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_SemanticObjectDto_(std::vector<SemanticObjectDto> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_SemanticObjectDto(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_ReferenceDto(ReferenceDto const& v) { rivet::Value::List r; r.reserve(5); r.push_back(encode_String(v.kind)); r.push_back(encode_String(v.source_path)); r.push_back(encode_String(v.source_element_path)); r.push_back(encode_String(v.target_path)); r.push_back(encode_Bool(v.resolved)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_ReferenceDto_(std::vector<ReferenceDto> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_ReferenceDto(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__Optional_String_(std::optional<std::string> const& v) { return v ? encode_String(*v) : rivet::Value{}; }
inline rivet::Value encode_WorkspaceSummary(WorkspaceSummary const& v) { rivet::Value::List r; r.reserve(10); r.push_back(encode_String(v.source_path)); r.push_back(encode_Int64(v.file_count)); r.push_back(encode_Int64(v.identifiable_count)); r.push_back(encode_Int64(v.package_count)); r.push_back(encode_Int64(v.reference_count)); r.push_back(encode_Int64(v.unresolved_count)); r.push_back(encode_Int64(v.duplicate_count)); r.push_back(encode_Int64(v.file_error_count)); r.push_back(encode__Optional_String_(v.autosar_release)); r.push_back(encode_Bool(v.mixed_schema)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_TraceDto(TraceDto const& v) { rivet::Value::List r; r.reserve(4); r.push_back(encode_String(v.root)); r.push_back(encode_Int64(v.max_depth)); r.push_back(encode__List_String_(v.node_paths)); r.push_back(encode__List_ReferenceDto_(v.edges)); return rivet::Value(std::move(r)); }
inline rivet::Value encode_Any(rivet::Value v) { return v; }

inline bool decode_Bool(rivet::Value const& v) { if (auto p = std::get_if<bool>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bool"); }
inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline std::vector<std::string> decode__List_String_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List String)"); std::vector<std::string> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_String(x)); return r; }
inline ClusterDto decode_ClusterDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: ClusterDto"); return ClusterDto{decode_String((*p)[0]), decode__List_String_((*p)[1]), decode__List_String_((*p)[2])}; }
inline std::vector<ClusterDto> decode__List_ClusterDto_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List ClusterDto)"); std::vector<ClusterDto> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_ClusterDto(x)); return r; }
inline CommunicationDto decode_CommunicationDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 4) throw std::runtime_error("Rivet result type mismatch: CommunicationDto"); return CommunicationDto{decode__List_ClusterDto_((*p)[0]), decode__List_String_((*p)[1]), decode__List_String_((*p)[2]), decode__List_String_((*p)[3])}; }
inline ObjectChangeDto decode_ObjectChangeDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: ObjectChangeDto"); return ObjectChangeDto{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_String((*p)[3]), decode_String((*p)[4])}; }
inline std::vector<ObjectChangeDto> decode__List_ObjectChangeDto_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List ObjectChangeDto)"); std::vector<ObjectChangeDto> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_ObjectChangeDto(x)); return r; }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
inline DiffDto decode_DiffDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 3) throw std::runtime_error("Rivet result type mismatch: DiffDto"); return DiffDto{decode_Bool((*p)[0]), decode__List_ObjectChangeDto_((*p)[1]), decode_Int64((*p)[2])}; }
inline SemanticObjectDto decode_SemanticObjectDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 6) throw std::runtime_error("Rivet result type mismatch: SemanticObjectDto"); return SemanticObjectDto{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_String((*p)[3]), decode_String((*p)[4]), decode_Int64((*p)[5])}; }
inline std::vector<SemanticObjectDto> decode__List_SemanticObjectDto_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List SemanticObjectDto)"); std::vector<SemanticObjectDto> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_SemanticObjectDto(x)); return r; }
inline ReferenceDto decode_ReferenceDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 5) throw std::runtime_error("Rivet result type mismatch: ReferenceDto"); return ReferenceDto{decode_String((*p)[0]), decode_String((*p)[1]), decode_String((*p)[2]), decode_String((*p)[3]), decode_Bool((*p)[4])}; }
inline std::vector<ReferenceDto> decode__List_ReferenceDto_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List ReferenceDto)"); std::vector<ReferenceDto> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_ReferenceDto(x)); return r; }
inline std::optional<std::string> decode__Optional_String_(rivet::Value const& v) { if (std::holds_alternative<std::monostate>(v.data)) return std::nullopt; return decode_String(v); }
inline WorkspaceSummary decode_WorkspaceSummary(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 10) throw std::runtime_error("Rivet result type mismatch: WorkspaceSummary"); return WorkspaceSummary{decode_String((*p)[0]), decode_Int64((*p)[1]), decode_Int64((*p)[2]), decode_Int64((*p)[3]), decode_Int64((*p)[4]), decode_Int64((*p)[5]), decode_Int64((*p)[6]), decode_Int64((*p)[7]), decode__Optional_String_((*p)[8]), decode_Bool((*p)[9])}; }
inline TraceDto decode_TraceDto(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p || p->size() != 4) throw std::runtime_error("Rivet result type mismatch: TraceDto"); return TraceDto{decode_String((*p)[0]), decode_Int64((*p)[1]), decode__List_String_((*p)[2]), decode__List_ReferenceDto_((*p)[3])}; }
inline rivet::Value decode_Any(rivet::Value const& v) { return v; }
}  // namespace detail

struct ProgressEvent { rivet::Value value; };
using Event = std::variant<ProgressEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "progress") return Event{ProgressEvent{detail::decode_Any(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<bool> close_workspace() { auto raw = backend_.call("close_workspace", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> bool { return detail::decode_Bool(raw.get()); }); }
  [[nodiscard]] std::uint64_t close_workspace_async(std::function<void(Result<bool>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("close_workspace", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<bool> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bool(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<CommunicationDto> communication() { auto raw = backend_.call("communication", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> CommunicationDto { return detail::decode_CommunicationDto(raw.get()); }); }
  [[nodiscard]] std::uint64_t communication_async(std::function<void(Result<CommunicationDto>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("communication", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<CommunicationDto> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_CommunicationDto(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DiffDto> diff_workspaces(std::string before, std::string after) { auto raw = backend_.call("diff_workspaces", rivet::Value::List{detail::encode_String(before), detail::encode_String(after)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DiffDto { return detail::decode_DiffDto(raw.get()); }); }
  [[nodiscard]] std::uint64_t diff_workspaces_async(std::string before, std::string after, std::function<void(Result<DiffDto>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("diff_workspaces", rivet::Value::List{detail::encode_String(before), detail::encode_String(after)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<DiffDto> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DiffDto(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<SemanticObjectDto>> find_objects(std::string pattern) { auto raw = backend_.call("find_objects", rivet::Value::List{detail::encode_String(pattern)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<SemanticObjectDto> { return detail::decode__List_SemanticObjectDto_(raw.get()); }); }
  [[nodiscard]] std::uint64_t find_objects_async(std::string pattern, std::function<void(Result<std::vector<SemanticObjectDto>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("find_objects", rivet::Value::List{detail::encode_String(pattern)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<SemanticObjectDto>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_SemanticObjectDto_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<ReferenceDto>> get_refs(std::string name_or_path) { auto raw = backend_.call("get_refs", rivet::Value::List{detail::encode_String(name_or_path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<ReferenceDto> { return detail::decode__List_ReferenceDto_(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_refs_async(std::string name_or_path, std::function<void(Result<std::vector<ReferenceDto>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("get_refs", rivet::Value::List{detail::encode_String(name_or_path)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<ReferenceDto>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_ReferenceDto_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DiffDto> impact_for_ecu(std::string before, std::string after, std::string ecu_name) { auto raw = backend_.call("impact_for_ecu", rivet::Value::List{detail::encode_String(before), detail::encode_String(after), detail::encode_String(ecu_name)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DiffDto { return detail::decode_DiffDto(raw.get()); }); }
  [[nodiscard]] std::uint64_t impact_for_ecu_async(std::string before, std::string after, std::string ecu_name, std::function<void(Result<DiffDto>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("impact_for_ecu", rivet::Value::List{detail::encode_String(before), detail::encode_String(after), detail::encode_String(ecu_name)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<DiffDto> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DiffDto(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<SemanticObjectDto>> list_ecus() { auto raw = backend_.call("list_ecus", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<SemanticObjectDto> { return detail::decode__List_SemanticObjectDto_(raw.get()); }); }
  [[nodiscard]] std::uint64_t list_ecus_async(std::function<void(Result<std::vector<SemanticObjectDto>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("list_ecus", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<SemanticObjectDto>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_SemanticObjectDto_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<SemanticObjectDto>> list_objects(std::string kind) { auto raw = backend_.call("list_objects", rivet::Value::List{detail::encode_String(kind)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<SemanticObjectDto> { return detail::decode__List_SemanticObjectDto_(raw.get()); }); }
  [[nodiscard]] std::uint64_t list_objects_async(std::string kind, std::function<void(Result<std::vector<SemanticObjectDto>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("list_objects", rivet::Value::List{detail::encode_String(kind)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<SemanticObjectDto>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_SemanticObjectDto_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<WorkspaceSummary> open_workspace(std::string path) { auto raw = backend_.call("open_workspace", rivet::Value::List{detail::encode_String(path)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> WorkspaceSummary { return detail::decode_WorkspaceSummary(raw.get()); }); }
  [[nodiscard]] std::uint64_t open_workspace_async(std::string path, std::function<void(Result<WorkspaceSummary>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("open_workspace", rivet::Value::List{detail::encode_String(path)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<WorkspaceSummary> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_WorkspaceSummary(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DiffDto> patch_apply(std::string workspace, std::string ops_json) { auto raw = backend_.call("patch_apply", rivet::Value::List{detail::encode_String(workspace), detail::encode_String(ops_json)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DiffDto { return detail::decode_DiffDto(raw.get()); }); }
  [[nodiscard]] std::uint64_t patch_apply_async(std::string workspace, std::string ops_json, std::function<void(Result<DiffDto>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("patch_apply", rivet::Value::List{detail::encode_String(workspace), detail::encode_String(ops_json)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<DiffDto> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DiffDto(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<DiffDto> patch_plan(std::string workspace, std::string ops_json) { auto raw = backend_.call("patch_plan", rivet::Value::List{detail::encode_String(workspace), detail::encode_String(ops_json)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> DiffDto { return detail::decode_DiffDto(raw.get()); }); }
  [[nodiscard]] std::uint64_t patch_plan_async(std::string workspace, std::string ops_json, std::function<void(Result<DiffDto>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("patch_plan", rivet::Value::List{detail::encode_String(workspace), detail::encode_String(ops_json)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<DiffDto> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_DiffDto(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<TraceDto> trace_from(std::string name_or_path, std::int64_t depth) { auto raw = backend_.call("trace_from", rivet::Value::List{detail::encode_String(name_or_path), detail::encode_Int64(depth)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> TraceDto { return detail::decode_TraceDto(raw.get()); }); }
  [[nodiscard]] std::uint64_t trace_from_async(std::string name_or_path, std::int64_t depth, std::function<void(Result<TraceDto>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("trace_from", rivet::Value::List{detail::encode_String(name_or_path), detail::encode_Int64(depth)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<TraceDto> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_TraceDto(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<ReferenceDto>> unresolved_references() { auto raw = backend_.call("unresolved_references", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<ReferenceDto> { return detail::decode__List_ReferenceDto_(raw.get()); }); }
  [[nodiscard]] std::uint64_t unresolved_references_async(std::function<void(Result<std::vector<ReferenceDto>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("unresolved_references", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<ReferenceDto>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_ReferenceDto_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<std::string>> validate_workspace() { auto raw = backend_.call("validate_workspace", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<std::string> { return detail::decode__List_String_(raw.get()); }); }
  [[nodiscard]] std::uint64_t validate_workspace_async(std::function<void(Result<std::vector<std::string>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("validate_workspace", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<std::string>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_String_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<WorkspaceSummary> workspace_summary() { auto raw = backend_.call("workspace_summary", rivet::Value::List{}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> WorkspaceSummary { return detail::decode_WorkspaceSummary(raw.get()); }); }
  [[nodiscard]] std::uint64_t workspace_summary_async(std::function<void(Result<WorkspaceSummary>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("workspace_summary", rivet::Value::List{}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<WorkspaceSummary> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_WorkspaceSummary(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
