// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "Autarx"
    public static let version = "2.0.0"
    public static let build: Int64 = 1
    public static let identifier = "site.jrtx.autarx.Autarx"
    public static let releaseChannel = "stable"
}

public struct ClusterDto: Sendable {
    public let path: String
    public let connected_ecus: [String]
    public let frames: [String]
    public init(path: String, connected_ecus: [String], frames: [String]) {
        self.path = path
        self.connected_ecus = connected_ecus
        self.frames = frames
    }
}

public struct CommunicationDto: Sendable {
    public let clusters: [ClusterDto]
    public let orphan_frames: [String]
    public let orphan_pdus: [String]
    public let orphan_signals: [String]
    public init(clusters: [ClusterDto], orphan_frames: [String], orphan_pdus: [String], orphan_signals: [String]) {
        self.clusters = clusters
        self.orphan_frames = orphan_frames
        self.orphan_pdus = orphan_pdus
        self.orphan_signals = orphan_signals
    }
}

public struct ObjectChangeDto: Sendable {
    public let change_type: String
    public let short_name: String
    public let semantic_kind: String
    public let absolute_path: String
    public let detail: String
    public init(change_type: String, short_name: String, semantic_kind: String, absolute_path: String, detail: String) {
        self.change_type = change_type
        self.short_name = short_name
        self.semantic_kind = semantic_kind
        self.absolute_path = absolute_path
        self.detail = detail
    }
}

public struct DiffDto: Sendable {
    public let identical: Bool
    public let object_changes: [ObjectChangeDto]
    public let reference_change_count: Int64
    public init(identical: Bool, object_changes: [ObjectChangeDto], reference_change_count: Int64) {
        self.identical = identical
        self.object_changes = object_changes
        self.reference_change_count = reference_change_count
    }
}

public struct ReferenceDto: Sendable {
    public let kind: String
    public let source_path: String
    public let source_element_path: String
    public let target_path: String
    public let resolved: Bool
    public init(kind: String, source_path: String, source_element_path: String, target_path: String, resolved: Bool) {
        self.kind = kind
        self.source_path = source_path
        self.source_element_path = source_element_path
        self.target_path = target_path
        self.resolved = resolved
    }
}

public struct SemanticObjectDto: Sendable {
    public let short_name: String
    public let element_type: String
    public let semantic_kind: String
    public let absolute_path: String
    public let source_file: String
    public let unresolved_references: Int64
    public init(short_name: String, element_type: String, semantic_kind: String, absolute_path: String, source_file: String, unresolved_references: Int64) {
        self.short_name = short_name
        self.element_type = element_type
        self.semantic_kind = semantic_kind
        self.absolute_path = absolute_path
        self.source_file = source_file
        self.unresolved_references = unresolved_references
    }
}

public struct TraceDto: Sendable {
    public let root: String
    public let max_depth: Int64
    public let node_paths: [String]
    public let edges: [ReferenceDto]
    public init(root: String, max_depth: Int64, node_paths: [String], edges: [ReferenceDto]) {
        self.root = root
        self.max_depth = max_depth
        self.node_paths = node_paths
        self.edges = edges
    }
}

public struct WorkspaceSummary: Sendable {
    public let source_path: String
    public let file_count: Int64
    public let identifiable_count: Int64
    public let package_count: Int64
    public let reference_count: Int64
    public let unresolved_count: Int64
    public let duplicate_count: Int64
    public let file_error_count: Int64
    public let autosar_release: String?
    public let mixed_schema: Bool
    public init(source_path: String, file_count: Int64, identifiable_count: Int64, package_count: Int64, reference_count: Int64, unresolved_count: Int64, duplicate_count: Int64, file_error_count: Int64, autosar_release: String?, mixed_schema: Bool) {
        self.source_path = source_path
        self.file_count = file_count
        self.identifiable_count = identifiable_count
        self.package_count = package_count
        self.reference_count = reference_count
        self.unresolved_count = unresolved_count
        self.duplicate_count = duplicate_count
        self.file_error_count = file_error_count
        self.autosar_release = autosar_release
        self.mixed_schema = mixed_schema
    }
}

private func encode_Bool(_ v: Bool) -> RivetValue { .bool(v) }
private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode__List_String_(_ v: [String]) -> RivetValue { .list(v.map(encode_String)) }
private func encode_ClusterDto(_ v: ClusterDto) -> RivetValue { .list([encode_String(v.path), encode__List_String_(v.connected_ecus), encode__List_String_(v.frames)]) }
private func encode__List_ClusterDto_(_ v: [ClusterDto]) -> RivetValue { .list(v.map(encode_ClusterDto)) }
private func encode_CommunicationDto(_ v: CommunicationDto) -> RivetValue { .list([encode__List_ClusterDto_(v.clusters), encode__List_String_(v.orphan_frames), encode__List_String_(v.orphan_pdus), encode__List_String_(v.orphan_signals)]) }
private func encode_ObjectChangeDto(_ v: ObjectChangeDto) -> RivetValue { .list([encode_String(v.change_type), encode_String(v.short_name), encode_String(v.semantic_kind), encode_String(v.absolute_path), encode_String(v.detail)]) }
private func encode__List_ObjectChangeDto_(_ v: [ObjectChangeDto]) -> RivetValue { .list(v.map(encode_ObjectChangeDto)) }
private func encode_Int64(_ v: Int64) -> RivetValue { .int64(v) }
private func encode_DiffDto(_ v: DiffDto) -> RivetValue { .list([encode_Bool(v.identical), encode__List_ObjectChangeDto_(v.object_changes), encode_Int64(v.reference_change_count)]) }
private func encode_SemanticObjectDto(_ v: SemanticObjectDto) -> RivetValue { .list([encode_String(v.short_name), encode_String(v.element_type), encode_String(v.semantic_kind), encode_String(v.absolute_path), encode_String(v.source_file), encode_Int64(v.unresolved_references)]) }
private func encode__List_SemanticObjectDto_(_ v: [SemanticObjectDto]) -> RivetValue { .list(v.map(encode_SemanticObjectDto)) }
private func encode_ReferenceDto(_ v: ReferenceDto) -> RivetValue { .list([encode_String(v.kind), encode_String(v.source_path), encode_String(v.source_element_path), encode_String(v.target_path), encode_Bool(v.resolved)]) }
private func encode__List_ReferenceDto_(_ v: [ReferenceDto]) -> RivetValue { .list(v.map(encode_ReferenceDto)) }
private func encode__Optional_String_(_ v: String?) -> RivetValue { v.map(encode_String) ?? .null }
private func encode_WorkspaceSummary(_ v: WorkspaceSummary) -> RivetValue { .list([encode_String(v.source_path), encode_Int64(v.file_count), encode_Int64(v.identifiable_count), encode_Int64(v.package_count), encode_Int64(v.reference_count), encode_Int64(v.unresolved_count), encode_Int64(v.duplicate_count), encode_Int64(v.file_error_count), encode__Optional_String_(v.autosar_release), encode_Bool(v.mixed_schema)]) }
private func encode_TraceDto(_ v: TraceDto) -> RivetValue { .list([encode_String(v.root), encode_Int64(v.max_depth), encode__List_String_(v.node_paths), encode__List_ReferenceDto_(v.edges)]) }
private func encode_Any(_ v: RivetValue) -> RivetValue { v }

private func decode_Bool(_ v: RivetValue) throws -> Bool { guard case .bool(let x) = v else { throw RivetGeneratedError.typeMismatch("Bool") }; return x }
private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode__List_String_(_ v: RivetValue) throws -> [String] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List String)") }; return try xs.map(decode_String) }
private func decode_ClusterDto(_ v: RivetValue) throws -> ClusterDto { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("ClusterDto") }; return ClusterDto(path: try decode_String(xs[0]), connected_ecus: try decode__List_String_(xs[1]), frames: try decode__List_String_(xs[2])) }
private func decode__List_ClusterDto_(_ v: RivetValue) throws -> [ClusterDto] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List ClusterDto)") }; return try xs.map(decode_ClusterDto) }
private func decode_CommunicationDto(_ v: RivetValue) throws -> CommunicationDto { guard case .list(let xs) = v, xs.count == 4 else { throw RivetGeneratedError.typeMismatch("CommunicationDto") }; return CommunicationDto(clusters: try decode__List_ClusterDto_(xs[0]), orphan_frames: try decode__List_String_(xs[1]), orphan_pdus: try decode__List_String_(xs[2]), orphan_signals: try decode__List_String_(xs[3])) }
private func decode_ObjectChangeDto(_ v: RivetValue) throws -> ObjectChangeDto { guard case .list(let xs) = v, xs.count == 5 else { throw RivetGeneratedError.typeMismatch("ObjectChangeDto") }; return ObjectChangeDto(change_type: try decode_String(xs[0]), short_name: try decode_String(xs[1]), semantic_kind: try decode_String(xs[2]), absolute_path: try decode_String(xs[3]), detail: try decode_String(xs[4])) }
private func decode__List_ObjectChangeDto_(_ v: RivetValue) throws -> [ObjectChangeDto] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List ObjectChangeDto)") }; return try xs.map(decode_ObjectChangeDto) }
private func decode_Int64(_ v: RivetValue) throws -> Int64 { guard case .int64(let x) = v else { throw RivetGeneratedError.typeMismatch("Int64") }; return x }
private func decode_DiffDto(_ v: RivetValue) throws -> DiffDto { guard case .list(let xs) = v, xs.count == 3 else { throw RivetGeneratedError.typeMismatch("DiffDto") }; return DiffDto(identical: try decode_Bool(xs[0]), object_changes: try decode__List_ObjectChangeDto_(xs[1]), reference_change_count: try decode_Int64(xs[2])) }
private func decode_SemanticObjectDto(_ v: RivetValue) throws -> SemanticObjectDto { guard case .list(let xs) = v, xs.count == 6 else { throw RivetGeneratedError.typeMismatch("SemanticObjectDto") }; return SemanticObjectDto(short_name: try decode_String(xs[0]), element_type: try decode_String(xs[1]), semantic_kind: try decode_String(xs[2]), absolute_path: try decode_String(xs[3]), source_file: try decode_String(xs[4]), unresolved_references: try decode_Int64(xs[5])) }
private func decode__List_SemanticObjectDto_(_ v: RivetValue) throws -> [SemanticObjectDto] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List SemanticObjectDto)") }; return try xs.map(decode_SemanticObjectDto) }
private func decode_ReferenceDto(_ v: RivetValue) throws -> ReferenceDto { guard case .list(let xs) = v, xs.count == 5 else { throw RivetGeneratedError.typeMismatch("ReferenceDto") }; return ReferenceDto(kind: try decode_String(xs[0]), source_path: try decode_String(xs[1]), source_element_path: try decode_String(xs[2]), target_path: try decode_String(xs[3]), resolved: try decode_Bool(xs[4])) }
private func decode__List_ReferenceDto_(_ v: RivetValue) throws -> [ReferenceDto] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List ReferenceDto)") }; return try xs.map(decode_ReferenceDto) }
private func decode__Optional_String_(_ v: RivetValue) throws -> String? { if case .null = v { return nil }; return try decode_String(v) }
private func decode_WorkspaceSummary(_ v: RivetValue) throws -> WorkspaceSummary { guard case .list(let xs) = v, xs.count == 10 else { throw RivetGeneratedError.typeMismatch("WorkspaceSummary") }; return WorkspaceSummary(source_path: try decode_String(xs[0]), file_count: try decode_Int64(xs[1]), identifiable_count: try decode_Int64(xs[2]), package_count: try decode_Int64(xs[3]), reference_count: try decode_Int64(xs[4]), unresolved_count: try decode_Int64(xs[5]), duplicate_count: try decode_Int64(xs[6]), file_error_count: try decode_Int64(xs[7]), autosar_release: try decode__Optional_String_(xs[8]), mixed_schema: try decode_Bool(xs[9])) }
private func decode_TraceDto(_ v: RivetValue) throws -> TraceDto { guard case .list(let xs) = v, xs.count == 4 else { throw RivetGeneratedError.typeMismatch("TraceDto") }; return TraceDto(root: try decode_String(xs[0]), max_depth: try decode_Int64(xs[1]), node_paths: try decode__List_String_(xs[2]), edges: try decode__List_ReferenceDto_(xs[3])) }
private func decode_Any(_ v: RivetValue) throws -> RivetValue { v }

public enum RivetEvent: Sendable {
    case progress(RivetValue)

    public static func decode(name: String, value: RivetValue) throws -> RivetEvent {
        switch name {
        case "progress": return .progress(try decode_Any(value))
        default: throw RivetGeneratedError.unknownEvent(name)
        }
    }
}

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func close_workspace() async throws -> Bool {
        let result = try await client.call("close_workspace", arguments: [])
        return try decode_Bool(result)
    }
    public func communication() async throws -> CommunicationDto {
        let result = try await client.call("communication", arguments: [])
        return try decode_CommunicationDto(result)
    }
    public func diff_workspaces(before: String, after: String) async throws -> DiffDto {
        let result = try await client.call("diff_workspaces", arguments: [encode_String(before), encode_String(after)])
        return try decode_DiffDto(result)
    }
    public func find_objects(pattern: String) async throws -> [SemanticObjectDto] {
        let result = try await client.call("find_objects", arguments: [encode_String(pattern)])
        return try decode__List_SemanticObjectDto_(result)
    }
    public func get_refs(name_or_path: String) async throws -> [ReferenceDto] {
        let result = try await client.call("get_refs", arguments: [encode_String(name_or_path)])
        return try decode__List_ReferenceDto_(result)
    }
    public func impact_for_ecu(before: String, after: String, ecu_name: String) async throws -> DiffDto {
        let result = try await client.call("impact_for_ecu", arguments: [encode_String(before), encode_String(after), encode_String(ecu_name)])
        return try decode_DiffDto(result)
    }
    public func list_ecus() async throws -> [SemanticObjectDto] {
        let result = try await client.call("list_ecus", arguments: [])
        return try decode__List_SemanticObjectDto_(result)
    }
    public func list_objects(kind: String) async throws -> [SemanticObjectDto] {
        let result = try await client.call("list_objects", arguments: [encode_String(kind)])
        return try decode__List_SemanticObjectDto_(result)
    }
    public func open_workspace(path: String) async throws -> WorkspaceSummary {
        let result = try await client.call("open_workspace", arguments: [encode_String(path)])
        return try decode_WorkspaceSummary(result)
    }
    public func patch_apply(workspace: String, ops_json: String) async throws -> DiffDto {
        let result = try await client.call("patch_apply", arguments: [encode_String(workspace), encode_String(ops_json)])
        return try decode_DiffDto(result)
    }
    public func patch_plan(workspace: String, ops_json: String) async throws -> DiffDto {
        let result = try await client.call("patch_plan", arguments: [encode_String(workspace), encode_String(ops_json)])
        return try decode_DiffDto(result)
    }
    public func trace_from(name_or_path: String, depth: Int64) async throws -> TraceDto {
        let result = try await client.call("trace_from", arguments: [encode_String(name_or_path), encode_Int64(depth)])
        return try decode_TraceDto(result)
    }
    public func unresolved_references() async throws -> [ReferenceDto] {
        let result = try await client.call("unresolved_references", arguments: [])
        return try decode__List_ReferenceDto_(result)
    }
    public func validate_workspace() async throws -> [String] {
        let result = try await client.call("validate_workspace", arguments: [])
        return try decode__List_String_(result)
    }
    public func workspace_summary() async throws -> WorkspaceSummary {
        let result = try await client.call("workspace_summary", arguments: [])
        return try decode_WorkspaceSummary(result)
    }
}
